### ISSUE TITLE
halp

### ISSUE THREAD

**Issue by okwme** [alex-bu-89/auslaenderbehoerde-termin#1]
do i need a selenium server running for webdriverio to work?

**Comment by alex-bu-89** [comment]
Hey @okwme ,
this lib is not ready...
But yes, you need to run a selenium server to start webdriverio.

```
npm install selenium-standalone@latest -g
selenium-standalone install
selenium-standalone start
```

Then you can do whatever you want with webdriverio :)
e.g. `node ./src/lib/checkAppointment.js`
